---
title: "Summary"
author: "Vincent La"
date: "June 14, 2017"
output: pdf_document
---

# Summary
While mental health is a difficult public health problem, this paper has shown that it is possible to build a decent predictive model with just a handful of easily attainable socioeconomic and lifestyle characteristics. For feelings of worthlessness, the probability threshold closest to a perfect classifier for a logistic regression model (TPR = 1, FPR = 0) gives a 58.4\% true positive and a 35.1\% false positive rate. Although this is far from perfect, this model is significantly better than guessing at random. Others may wish to build upon this model to achieve better rates, working with the predictors identified to build a model more suitable for medical use. However, this model may also be put to immediate use. For example, those trying to raise awareness about mental health issues, or trying to offer services, should target areas with high unemployment rates, high poverty rates, and a larger proportion of unmarried individuals.

## Best Model: Logistic Regression
In conclusion, I choose logistic regression as the best model presented in this paper. Firstly, it simply performs better than the other models. While when looking at the testing set, it performances similarly to other models in terms of the F1 score and ROC curve, it has higher precision. Likewise, the logistic regression model is the only model which has similar behavior in both the training and testing sets. This suggests that it will behave similarly if applied to outside data, unlike the other models which had a sharp drop of performance (when looking at the F1 score or precision-recall curve) when applied to the testing data.

Furthermore, most of the papers cited by this project also utilized logistic regression models. There are several reasons why this is the case. First, while decision trees and logistic regression models are both readily interpretable, logistic regressions are much more concise. While a fitted logistic regression can be expressed as a single mathematical formula, a complicated decision tree can take up a page or more. Moreover, decision trees did not include some significant predictors identified by the logistic regression model--especially sex. As shown in earlier graphs, women were much more likely to develop symptoms of depression--a fact which is corroborated by outside research. Given the sample size of the data set, this is not a random fluke. Yet despite its importance, none of the decision trees included sex as a significant predictor, suggesting that they may not be a good method of identifying important risk factors.

## Limitations
This problem this paper deals with is classification. As such, the purpose was to include was many covariates as possible in order to increase the accuracy of predictive models. This method allows us to analyze the relative importance of various socioeconomic, medical, and lifestyle factors as risk factors for mental distress. However, the main drawback is that the relationships between specific covariates and the response were not examined very throughly. While some nonlinear and interaction effects were considered, many more were not due to the scope of this paper. Many of the covariates in this model were included in linear form and interested researchers may wish to examine these relationships more thoroughly.

Furthermore, due to time constraints, some interesting attributed contained in the NHIS were not examined. For example, while this paper examined the relationship between being married and mental distress, it did not examine the relationship between divorce and mental distress. While the relationship between disability and depression was briefly examined through the inclusion of not being able to work due to disability as a predictor, others may wish the study the relationship between the nature and severity disability and depression. Lastly, sexual orientation was not studied in this paper because it was only recently introduced as an item in the 2013 National Health Interview Survey.